name: Bug Report
description: Create a bug report
labels: ['template: bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: markdown
    attributes:
      value: |
        If you follow all of the instructions carefully, and your account / IP hasn't been permanently flagged by Cloudflare / OpenAI, then you shouldn't ever get a 403 at this point.
  - type: markdown
    attributes:
      value: |
        My Twitter bot has been running for the past 2 days without a single 403, and others have been able to get it working on Discord. Although it can take a bit of effort to get working, once you have it working, you're set.
  - type: checkboxes
    attributes:
      label: Verify latest release
      description: '`chatgpt@latest` is the latest version of `chatgpt`. Some issues may already be fixed in the latest version, so please verify that your issue reproduces before opening a new issue.'
      options:
        - label: I verified that the issue exists in the latest `chatgpt` release
          required: true
  - type: checkboxes
    attributes:
      label: Verify webapp is working
      description: 'Verify that the [ChatGPT webapp](https://chat.openai.com/) is working for you locally using the same browser and account.'
      options:
        - label: I verify that the ChatGPT webapp is working properly for this account.
          required: true
  - type: checkboxes
    attributes:
      label: Verify resrictions
      description: Verify that you've double-checked all of the [restrictions](https://github.com/transitive-bullshit/chatgpt-api#restrictions) listed in the readme.
      options:
        - label: I verify that I've double-checked all of the restrictions.
          required: true
 - type: textarea
    attributes:
      label: Provide environment information
      description: Please enter `node --version`, `Chrome` version, OS, OS version.
    validations:
      required: true
