name: Feature Request
description: Create a feature rqeuest
labels: ['template: enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request.
  - type: textarea
    attributes:
      label: Describe the feature
      description: What would you like to see added / supported?
    validations:
      required: true
